export const App = {
    name: 'Arround Viet Nam',
    version: '0.0.1',
    welcomeText: 'Khám phá Việt Nam cùng Around Vietnam! Tìm kiếm những điều thú vị, thưởng thức ẩm thực địa phương',
    defaultLanguage: 'vi',
    languages: ['vi', 'en'],
    routes: {
        home: '/',
        login: '/login',
        register: '/register',
        dashboard: '/dashboard',
        forgotPassword: '/forgot-password',
        resetPassword: '/reset-password',
        profile: '/profile',
        settings: '/settings',
        about: '/about',
        contact: '/contact',
        terms: '/terms',
        privacy: '/privacy',
        notFound: '/404',
    },
}